services:
  core:
    build:
      dockerfile: ./Dockerfile
    tty: true
    environment:
      PYTHONPATH: /opt/src
    volumes:
      - "${PWD}/src:/opt/src/"
      - "${PWD}/.env:/opt/src/.env"
      - "${PWD}/entrypoint.sh:/opt/entrypoint.sh"
    working_dir: /opt/src/
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: ["/bin/bash", "/opt/entrypoint.sh"]
  postgres:
    image: postgres:11
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: analytics
      PGUSER: postgres
    ports:
      - "54322:5432"
    volumes:
      - "${PWD}/db-data:/var/lib/postgresql/data"
      - "./init_scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      retries: 10
      start_period: 10s
